version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=/app/db.sqlite3  # SQLite database file path
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]